### ISSUE TITLE
Question: renderToHardwareTextureAndroid needed?

### ISSUE THREAD

**Issue by cristianoccazinsp** [ascoders/react-native-image-zoom#106]
Is renderToHardwareTextureAndroid needed? Does it have any side effect on the memory if not using it?
https://github.com/ascoders/react-native-image-zoom/blob/master/src/image-zoom/image-zoom.component.tsx#L668

I'm asking this because I've seen out of memory errors on some devices when trying to load a picture with this component. I can't consistently reproduce it as it seems very specific to some devices, but it was related to this and using a placeholder png image.

**Comment by mtford90** [comment]
I seem to face these memory errors on Android 7. Anything above that works fine.

**Comment by ArtemKolichenkov** [comment]
closed with #112
