### ISSUE TITLE
Can't pan on initial load, how to see all of the image on load

### ISSUE THREAD

**Issue by markdaws** [ascoders/react-native-image-zoom#11]
I have the following code, cropWidth/cropHeight are set to the size of the screen:

      let cropWidth = 375
      let cropHeight = 667

      let imageWidth = 3401
      let imageHeight = 1603

      imageViewer = (
        <ImageZoom
          cropWidth={cropWidth}
          cropHeight={cropHeight}
          imageWidth={imageWidth}
          imageHeight={imageHeight}
        >
          <Image
            source={{ uri: image.url }}
            //resizeMode="contain"
            style={{
              width: imageWidth,
              height: imageHeight,
            }}
          />
        </ImageZoom>

When the image loads it is at some zoom level, centered on the middle of the image, but I can't see the whole image and can't pan at all, it just jumps back to the middle as I try to pan. If I zoom in a little bit then it will let me pan around.

How can I get the whole image to be visible on load?  I tried setting resizeMode="contain" on the image but that didn't do anything?

**Comment by ascoders** [comment]
Try use `centerOn`:

```javascript
<ImageZoom
    centerOn={{
        x: 0, y: 0, scale: 0.5, duration: 100
    }}
>
```
