### ISSUE TITLE
ComponentWillMount, componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by alinleonard** [ascoders/react-native-image-zoom#111]
Hello,

Did someone already fixed the warnings ?

` Warning: componentWillMount is deprecated and will be removed in the next major version. Use componentDidMount instead. As a temporary workaround, you can rename to UNSAFE_componentWillMount.`

`Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.`

I would appreciate it !

**Comment by NinjaAniket** [comment]
Just put it inside YellowBox warnings would be removed check the link below.
[https://reactnativecode.com/solve-warning-componentwillmount-is-deprecated/](url)

**Comment by alinleonard** [comment]
@NinjaAniket thanks for the info, but this won't solve the issue, the lifecycle will be deprecated

**Comment by chetan-zalake** [comment]
Any updates on this?

**Comment by chetan-zalake** [comment]
@ascoders : When will this get updated?

**Comment by robert-narrate** [comment]
bump

**Comment by pkozhin** [comment]
Hi, please fix the deprecated react lifecycle methods.
react-native-image-zoom-viewer (which is quite widely used) also depends on this library.

**Comment by cuongnm2301** [comment]
any solution ?

**Comment by sachinshettigar** [comment]
@ascoders  any plans to fix these warnings?

**Comment by astriskit** [comment]
@ascoders - came across the warning while using the `react-native-image-zoom-viewer`; #121 should help - let me know what do you think about it.

**Comment by astriskit** [comment]
btw `kudos` for such a nice utility @ascoders - thanks.

**Comment by cristianoccazinsp** [comment]
Any updates? Can the PRs be merged? https://github.com/ascoders/react-native-image-zoom/pull/114

**Comment by claudiozam** [comment]
+1

**Comment by piotrponikowski** [comment]
@ascoders any plans for merge?
