### ISSUE TITLE
Scale prop?

### ISSUE THREAD

**Issue by feluxz** [ascoders/react-native-image-zoom#14]
Hello, i want to be able to reset the scale on call. How could i do this? Just like when double clicked it goes back to full scale.

**Comment by capslock35** [comment]
any solution for this problem ?

**Comment by ascoders** [comment]
Why you want to control this scale outside?

**Comment by capslock35** [comment]
I have images in array, and I get them array[this.state.index] . İf I zoom
in and change the index, the image changes but it is still zoomed in

**Comment by simonvdfr** [comment]
@ascoders I am interested in the ability to change the zoom state from a button. For example to return to the original scale or a zoom x2...
