### ISSUE TITLE
建议加一个缩放的回调方法

### ISSUE THREAD

**Issue by RockyF** [ascoders/react-native-image-zoom#15]
如题，建议加一个缩放的回调或者在responderRelease里把当前scale值加上，但是responderRelease需要在onPanResponderRelease的最后面调用，这样scale就是最终值了。

**Comment by ascoders** [comment]
有用到缩放参数吗？

**Comment by RockyF** [comment]
恩，因为需求是在图片方大的时候不能拖动ListView，需要在得知ZoomImage的缩放为1的情况下才能拖动ListView，所以在responderRelease里获取到scale，根据scale来设定ListView的scrollEnable就能满足需求。
还有responderRelease需要在onPanResponderRelease的最后面调用，这样scale就是最终值了。

**Comment by ascoders** [comment]
merged.
