### ISSUE TITLE
加载网络图片有的图加载不出来请问是为什么

### ISSUE THREAD

**Issue by lizhuoyuan** [ascoders/react-native-image-zoom#17]
source={{uri: 'http://static.statickksmg.com/image/2017/05/23/ce0c8daecee18e63311bda3c9dd4be45.jpg'}}/>

例子上的图片我也加载不出来,但是有的网络图片可以,不知道为什么

**Comment by mironovpib101** [comment]
use default Image

> code

 <ImageZoom >
                        <Image
                            style={GalleryStyle.detailImage}
                            resizeMode={Image.resizeMode.cover}
                            source={this.state.photo}
                            onError={()=>this.setState({photo:require("resource/images/not-photo.png")})}
                        />
                    </ImageZoom>

> where

this.state.photo = {uri: 'http://static.statickksmg.com/image/2017/05/23/ce0c8daecee18e63311bda3c9dd4be45.jpg'}
