### ISSUE TITLE
ImageZoom blocks child TouchableOpacity's onPress working

### ISSUE THREAD

**Issue by DavitVosk** [ascoders/react-native-image-zoom#22]
Thanks for your awesome package, it is amazing and so so helpful.
I faced some problems here: when the children of ImageZoom is TouchableOpacity, then the onPress prop is not working at all. I think something blocks its working (PanResponder or something else). Please help to solve the problem. Thnaks 

Regards,
David

**Comment by ascoders** [comment]
It's better to disable children `TouchableOpacity`, when you want to scale it?

**Comment by DavitVosk** [comment]
I am using ImageZoom to wrap the image to be zoomed. Also, on the image I need some rectangles which should be pressable to alert some data. So now when I press on these rectangles (created with TouchableOpacity having onPress prop) I receive nothing.

**Comment by DavitVosk** [comment]
I found http://browniefed.com/blog/react-native-maintain-touchable-items-with-a-parent-panresponder/ article, where it is mentioned that This line onMoveShouldSetPanResponder:(evt, gestureState) => true always returns true so the element will always accept. Also we aren’t using the capture phase so the TouchableOpacity will always be pressable.

**Comment by DavitVosk** [comment]
So I think  
            onMoveShouldSetPanResponderCapture: (_evt, gestureState) => {
                return setResponder && gestureState.dx != 0 && gestureState.dy != 0;
            }
should be removed from the package. What do you think?

**Comment by ascoders** [comment]
Maybe.. , is it worked fine? You can try first.

**Comment by DavitVosk** [comment]
I should delete it from node-modules/react-native-image-pan-zoom / image-zoom.component.tsx file ?

**Comment by ascoders** [comment]
`node_modules/react-native-image-pan-zoom/built/image-zoom/image-zoom.component.js`

**Comment by DavitVosk** [comment]
yes, it worked.

Could you please remove onStartShouldSetPanResponderCapture: (evt, gestureState) => setResponder,
 onMoveShouldSetPanResponder: (evt, gestureState) => setResponder and onMoveShouldSetPanResponderCapture: (evt, gestureState) => setResponder lines (in total 3 lines) from the package?

**Comment by ascoders** [comment]
Thanks a lot! Try `react-native-image-pan-zoom@2.0.7`.
