### ISSUE TITLE
Is there an option to center the image at some part of it

### ISSUE THREAD

**Issue by DavitVosk** [ascoders/react-native-image-zoom#23]
Hi again.
Can you please advise whether there is an option to center the image at some part of it. For example, I want the (x,y) point to be the center of my mobile screen. Is there any option for it? Thanks

**Comment by mironovpib101** [comment]
Привет! Положите своё изображение в View и настройте стили, почему бы и нет?

**Comment by ascoders** [comment]
It's ok, and welcome PR!

**Comment by a-r-d** [comment]
@DavitVosk I just opened a PR to do this and it was merged. It allows you to pan and zoom using a property called ```centerOn```
