### ISSUE TITLE
How to make a image scrolling?

### ISSUE THREAD

**Issue by yourcontainer** [ascoders/react-native-image-zoom#24]
Have a conflict with this library, can not be change the pages, events doesn't fired
https://www.npmjs.com/package/react-native-viewpager

**Comment by mironovpib101** [comment]
Use this.onMove and  this.swap for update next/this/prev image  

> Code


<Image
                        style={GalleryStyle.detailImage}
                        source={this.state.rightImage}
                        onError={()=>this.setState({rightImage:require("resource/images/not-photo.png")})}
                    />
                    <ImageZoom
                        onClick={()=>this.setState({show: !this.state.show})}
                        doubleClickInterval={1}
                        ref={ref=>this._image = ref}
                        cropWidth={window.width}
                        cropHeight={window.height}
                        imageWidth={window.width}
                        imageHeight={window.height}
                        responderRelease={this.swap}
                        maxOverflow={100}
                        horizontalOuterRangeOffset={this.onMove}
                    >
                        <Image
                            style={GalleryStyle.detailImage}
                            resizeMode={Image.resizeMode.cover}
                            source={this.state.photo}
                            onError={()=>this.setState({photo:require("resource/images/not-photo.png")})}
                        />
                    </ImageZoom>
                    <Image
                        style={GalleryStyle.detailImage}
                        source={this.state.leftImage}
                        onError={()=>this.setState({leftImage:require("resource/images/not-photo.png")})}
                    />

**Comment by sroze** [comment]
What are these `this.swap` and `this.onMove` ?

**Comment by TheMarsGuy** [comment]
`horizontalOuterRangeOffset` is never called.

**Comment by mironovpib101** [comment]
my created function
onMove = offset => {
      //save offset image 
};
swap = () => {
     // testing offset for swap image
}
