### ISSUE TITLE
Weird behavior with image

### ISSUE THREAD

**Issue by sidferreira** [ascoders/react-native-image-zoom#25]
I'm working on an app and there are 3 images that, by any reason, doesn't work properly.
Those were just sample images I picked and to my surprise, they don't work properly.
I checked the image size and it's all right. There are other images that are working just fine.

The images are minified, not sure if it changes anything. The images start zoomed and if I try to zoom in or out, it gets back to the initial size (will send a video later)

![error_cable_1](https://user-images.githubusercontent.com/143615/31273573-a542b9f6-aa65-11e7-922b-220f544aeee4.jpg)
![error_cable_2](https://user-images.githubusercontent.com/143615/31273574-a543ac62-aa65-11e7-9ccc-3a72c5f6f449.jpg)
![error_miriam](https://user-images.githubusercontent.com/143615/31273575-a54434fc-aa65-11e7-9b19-ee92beba269e.jpg)

The code in use:
```
          <ImageZoom cropWidth={width} cropHeight={height} imageWidth={original_w} imageHeight={original_h}>
            <Image style={{width: original_w, height: original_h}} source={{uri: publicMainUrl}} />
          </ImageZoom>
```

`width` and `height` are the device sizes. `original_w` and `original_h` are properly set based on the image sizes.

**Comment by VBarzionov** [comment]
Hello,
I have the same issue..
The problem get critical with large (e.g. photo) images.

I diged into sources and try make a guess about reason...
The Lib actually uses Transformation of View's style props to pan/scale over Image.
On the init it set Scale to 1 - we look at Image 1:1. (this cause very zoomed initial view on Photos)

latter In onPanResponderRelease() method the lib cheks 
if (this.scale < 1) {
   this.scale = 1

   .... init view to default

This means if we zoom-out more than 1:1 the Lib resets view to default.
We have to zoom-in to be able Pan Image. 
The probable solution is correct init minimal scale with respect to Image/Crop sizes.
