### ISSUE TITLE
How to change black background color?

### ISSUE THREAD

**Issue by vijay-dadhich09** [ascoders/react-native-image-zoom#28]
Is there any property to changes background color. Default is black. Can I do it transparent.

**Comment by ascoders** [comment]
The default background color is transparent - https://github.com/ascoders/react-native-image-zoom/blob/master/image-zoom/image-zoom.style.ts#L8, what's wrong?

**Comment by ascoders** [comment]
See https://github.com/ascoders/react-native-image-zoom/blob/master/src/image-zoom/image-zoom.style.ts#L7.
