### ISSUE TITLE
Double tap problem with resizeMode contain

### ISSUE THREAD

**Issue by jjdp** [ascoders/react-native-image-zoom#32]
I'm getting this weird behavior when i double tap.

![video-1513917119](https://user-images.githubusercontent.com/5244520/34285525-38e136c4-e715-11e7-92bc-d3498a153028.gif)

**Comment by charmer1989** [comment]
我也觉得双击处理的有待优化, 个人尝试了一下:

**Comment by ascoders** [comment]
很棒，前几天我已经处理过了，方式和你的几乎一样，现在就可以升级到最新版体验。
