### ISSUE TITLE
No matching version found for react-native-image-pan-zoom@2.0.15

### ISSUE THREAD

**Issue by 594904020** [ascoders/react-native-image-zoom#33]
No matching version found for react-native-image-pan-zoom@2.0.15

**Comment by ascoders** [comment]
This latest version for [react-native-image-pan-zoom](https://www.npmjs.com/package/react-native-image-pan-zoom) is `2.0.16`

This latest version for [react-native-image-zoom-viewer](https://www.npmjs.com/package/react-native-image-zoom-viewer) is `2.0.18`
