### ISSUE TITLE
Can't pan without zooming.

### ISSUE THREAD

**Issue by TDLehman** [ascoders/react-native-image-zoom#39]
When an image is loaded initially with a scale of 1, if you try panning it will just jump back to the middle of the photo. If you zoom in at all it will allow you to pan as expected.       
centerOn={{
        x: 0,
        y: 0,
        scale: 1.01,
        duration: 100
      }}
works as a workaround, but if you reset the image with a double press you will no longer be able to pan again.

**Comment by ascoders** [comment]
Yes, the initial scale can't be pan, because it has been full displayed in the screen.
