### ISSUE TITLE
is it need to build?

### ISSUE THREAD

**Issue by mmz211** [ascoders/react-native-image-zoom#40]
I used react-native-image-zoom in react native project.

I modified image-zoom/image-zoom.component.tsx and reload it from top view. but what I see from this url (http://127.0.0.1:8081/index.ios.bundle?platform=ios&dev=true&minify=false), is the original source of react-native-image-zoom.

I'd like to know if it needed to build after modification? As I see build folder in the source dictionary.
And how to build it? "tsc index.ts"?

**Comment by mmz211** [comment]
"tsc index.ts" failed

bash-3.2$ tsc index.ts 
index.ts(1,23): error TS6142: Module './image-zoom/image-zoom.component' was resolved to '/Users/admin/Workspace/TestSVN/node_modules/react-native-image-pan-zoom/image-zoom/image-zoom.component.tsx', but '--jsx' is not set.

**Comment by mmz211** [comment]
"tsc index.ts --jsx react" is right.

I guessed "tsc index.ts --jsx".

New problem while compiling
"image-zoom/image-zoom.component.tsx(95,135): error TS2339: Property 'props' does not exist on type 'ImageViewer' "

**Comment by ascoders** [comment]
You can see develop document [here](https://github.com/ascoders/react-native-image-zoom#development-pattern).

**Comment by ArtemKolichenkov** [comment]
I will update development docs soon as part of #129

**Comment by ArtemKolichenkov** [comment]
Closing this issue, dev docs will be improved when #131 closes.
