### ISSUE TITLE
How to remove Image Bounce effect during pan

### ISSUE THREAD

**Issue by SatVel** [ascoders/react-native-image-zoom#47]
Hi,

I tried the component and the zoom is working perfect for me however when I try to pan the image it has a bounce back effect when the mouse is released (on the emulator). I have not yet tried this on a physical device, but I guess that the bounce effect would be similar on the device as well. Could you kindly let me know if there is a way to disable this bounce effect on pan?
I have set the panToMove prop to true.

Thanks and Regards
Satyen Velankar

**Comment by ascoders** [comment]
Hello @SatVel , you may have triggered swipe down. You can disable it by pass `enableSwipeDown=true`.

**Comment by SatVel** [comment]
@ascoders :- Hi Thanks for your reply, I tried passing enableSwipeDown=true as a prop to the component, but that does not work for me. The behaviour that I am experiencing is as follows:-

I am having a large image inside a scroll view which is wrapped into your zoom component in the following manner:-

render() {
        return (
        <ScrollView>
           <ScrollViewChild scrollDirection={'both'}>
            <ImageZoom cropWidth={Dimensions.get("window").width}
                       cropHeight={Dimensions.get("window").height}
                       imageWidth={800}
                       imageHeight={800}
                       panToMove={true}
                       pinchToZoom={true}
                       enableSwipeDown={true}>
            <ImageBackground
                {...this.props}
                onLayout={this.resize}
                onLoad={this.onLoad}
                onLoadStart={this.onLoadStart}
                onLoadEnd={this.onLoadEnd}
                source={this.props.source}
                resizeMode="stretch"
                style={[
                    this.style,
                    this.getStyle(),
                    {height: this.state.height},
                    styles.container,
                ]}
            >
                {this.renderChildren()}

            </ImageBackground>

            </ImageZoom>
       </ScrollViewChild>
    </ScrollView>
        );
    }

The image zoom is working as expected, but when I swipe down to see the hidden part of the image and release my finger, it bounces back to the state in which it was and I am again unable to see the hidden part of the image which I want to see. I want to stop this bounce back on release feature. I want the image to stay at the same position when it was swiped down. Any ideas on how to achieve this?

Thanks and Regards
Satyen

**Comment by SatVel** [comment]
Hi Thanks for your reply, I tried passing enableSwipeDown=true as a prop to the component, but that does not work for me. The behaviour that I am experiencing is as follows:-

I am having a large image inside a scroll view which is wrapped into your zoom component in the following manner:-

render() {
return (

<ScrollViewChild scrollDirection={'both'}>
<ImageZoom cropWidth={Dimensions.get("window").width}
cropHeight={Dimensions.get("window").height}
imageWidth={800}
imageHeight={800}
panToMove={true}
pinchToZoom={true}
enableSwipeDown={true}>
<ImageBackground
{...this.props}
onLayout={this.resize}
onLoad={this.onLoad}
onLoadStart={this.onLoadStart}
onLoadEnd={this.onLoadEnd}
source={this.props.source}
resizeMode="stretch"
style={[
this.style,
this.getStyle(),
{height: this.state.height},
styles.container,
]}
>
{this.renderChildren()}

        </ImageBackground>

        </ImageZoom>
   </ScrollViewChild>
</ScrollView>
    );
}

**Comment by ascoders** [comment]
I'm sorry to made a mistake, the right way to disable swipe down is `enableSwipeDown=false`.

**Comment by SatVel** [comment]
@ascoders- No! I don't want to disable swipe down! I just want to retain the posiition of the image when it is swiped down. It should not jump back when I release the finger. Any clues on this?

Thanks and Regards
Satyen

**Comment by SatVel** [comment]
@ascoders- Perfect! setting swipeDownThreshold works like a charm! However, in my case I had to set it to -1 instead of 0 and now the bouncing effect has stopped! Thanks a lot for the help! I am closing this now.

Regards
Satyen

**Comment by faxioman** [comment]
I'm not finding a way to disable the bounce effect. Setting swipeDownThreshold to -1 disable the bounce effect but now I can drag the image out of canvas.
@ascoders I think that a prop like "enableSwipeDownBounceEffect" could be a great feature ;)

**Comment by VicEsquivel** [comment]
When I zoom in a picture, I am able to move it around freely and even out of the canvas vertically, with the props as shown below. 
```javascript
<ImageZoom 
	cropWidth={ Dimensions.get('window').width }
	cropHeight={ Dimensions.get('window').height }
	imageWidth={ imageActuallWidth }
	imageHeight={ imageActualHeight }>
```
I am unable to activate the bounce behavior. 

For my particular use, the fact that the user is able to move it away from the screen is a bigger issue than having it bounce back to the non-zoomed version of it... 

How can I enable the default bounce behavior for the image to not exit vertically in the canvas?

**Comment by aravi365** [comment]
> I'm not finding a way to disable the bounce effect. Setting swipeDownThreshold to -1 disable the bounce effect but now I can drag the image out of canvas.
> @ascoders I think that a prop like "enableSwipeDownBounceEffect" could be a great feature ;)

you fixed this or any workarounds? i can see a lot of space at top and bottom when `swipeDownThreshold={-1}`
