### ISSUE TITLE
Error: in this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.

### ISSUE THREAD

**Issue by mshibl** [ascoders/react-native-image-zoom#59]
I'm getting the following error when using ImageZoom, any idea what might be causing this?

<img width="272" alt="iphone 6 - 11 4 2018-06-13 11-24-05" src="https://user-images.githubusercontent.com/11624249/41371628-cd1de806-6eff-11e8-9dad-0bbe9f4aad35.png">

The code we're using is pretty straight forward:
```
<ImageZoom
    style={styles.imageContainer}
    cropWidth={Dimensions.get("window").width}
    cropHeight={Dimensions.get("window").height}
    imageWidth={Dimensions.get("window").width}
    imageHeight={240}
>
    <Image
        style={styles.image}
        source={imgSrc}
    />
</ImageZoom>
```

**Comment by mshibl** [comment]
We're running the latest version `2.1.3` and still getting the same issue

**Comment by mshibl** [comment]
I found a fix for this issue, it turns out what's causing this issue is passing `styles. imageContainer` to the `style` prop in `ImageZoom`

so the following works:
```
<ImageZoom
    style={{flex: 1}}
    cropWidth={Dimensions.get("window").width}
    cropHeight={Dimensions.get("window").height}
    imageWidth={Dimensions.get("window").width}
    imageHeight={240}
>
    <Image
        style={styles.image}
        source={imgSrc}
    />
</ImageZoom>
```

while this is good as a temporary fix, I think it's better if you allow for passing a react-native `StyleSheet` to the style prop.

Thank you for your fast reply, and for all the work you're doing on this project, we really appreciate it!

**Comment by ascoders** [comment]
#60 has merged, thanks @miketoth and @mshibl !
