### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by L-Jovi** [ascoders/react-native-image-zoom#6]
thanks for your smart library, I find that npm warn be throwed after install it like below image show.

![wechatimg107](https://cloud.githubusercontent.com/assets/7262199/26088363/6273812a-3a29-11e7-9f78-8efb291b2a20.jpeg)

Is it necessary to care about this warn message?

version
react-native 0.44
react 16.0.0-alpha.6

thanks for your time,

regards

**Comment by ascoders** [comment]
Hi @L-Jovi , it's just a warning, without any side effects.
I also published `2.0.2` to fix to, thanks a lot!

**Comment by L-Jovi** [comment]
@ascoders  thanks for your reply.
