### ISSUE TITLE
[Q] Is it possible to change default index programmatically?

### ISSUE THREAD

**Issue by AlirezaAkbarix** [ascoders/react-native-image-zoom#63]
I have a `Swiper` at my screen that shows product images, user swaps and changes the index of the slider, user is seeing third image now (e.g) now clicks on image and as I'm just sending image array to `ImageZoom` it shows the first image by default, Am I able to pass the index I want to see the third image at `ImageZoom`?

**Comment by jerearaujo03** [comment]
@AlirezaAkbarix did you solved it?

**Comment by jerearaujo03** [comment]
I found the way:

`<ImageViewer imageUrls={images} index={1}/>`

You have to use 'index' prop

**Comment by brycehanscomb** [comment]
Is this more related to the sister repo, https://github.com/ascoders/react-native-image-viewer than this one?

**Comment by ArtemKolichenkov** [comment]
Yes, you need to use [react-native-image-viewer](https://github.com/ascoders/react-native-image-viewer) for that. Or some other package altogether.  
This package isn't really built to work with other swipers out of the box. I mean it can, but you'll have to figure out it for your specific case. 🙁
