### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by oneroman** [ascoders/react-native-image-zoom#66]
Hi all,

I am using RN 55 and @types/react-native version 0.55.13 and while compilation I am having this issue:

When I use this library I am having
`node_modules/react-native-image-pan-zoom/src/image-zoom/image-zoom.component.tsx:17:92 - error TS2339: Property userAgent does not exist on type Navigator.
17     return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);`

any thoughts?

**Comment by ascoders** [comment]
Try `react-native-image-pan-zoom@2.1.10`

**Comment by oneroman** [comment]
@ascoders confirmed; it is fixed. Thank you.

**Comment by ghost** [comment]
I am using below three component to edit my photo. I am using **react-native-image-pan-zoom** to do panZoom for image crop. I want to save the cropped image but it shows me this error : "Surface#2 children does not contain any discoverable Node"
`import { Surface } from 'gl-react-expo';
import ImageFilters from 'react-native-gl-image-filters';
import ImageZoom from 'react-native-image-pan-zoom';`

```
<Surface style={{ width: 200, height:200}} ref={ref => (this.image = ref)}>
 <ImageZoom cropWidth={200}
                       cropHeight={200}
                       imageWidth={200}
                       imageHeight={200}> 
          <ImageFilters {...this.state} width={200} height={200}>
              {{ uri: 'https://i.imgur.com/5EOyTDQ.jpg' }}
            </ImageFilters>
 </ImageZoom>
 </Surface>
 
```

can anyone help me to crop an image using zoom in or zoom out or by using a normal border selector with fixed ratio?
