### ISSUE TITLE
执行 tsc 的时候出现一个 Error

### ISSUE THREAD

**Issue by hqwlkj** [ascoders/react-native-image-zoom#67]
错误信息：

> node_modules/react-native-image-pan-zoom/src/image-zoom/image-zoom.component.tsx:17:92 - error TS2339: Property 'userAgent' does not exist on type 'Navigator'.

![image](https://user-images.githubusercontent.com/12181423/46079886-fd2dec80-c1ca-11e8-95b6-d0c00edc7389.png)

**Comment by ascoders** [comment]
更新到最新版即可
