### ISSUE TITLE
Screen Tearing on Pan

### ISSUE THREAD

**Issue by jwhiddent3** [ascoders/react-native-image-zoom#72]
Only tested this on iOS so far, but for our use case, we have an ImageBackground with some views overlaid on it, inside the ImageZoom. The zooming works perfectly, but panning causes very apparent screen Tearing, worse the faster the pan (slow enough, not visible/noticeable, but has to be very slow). This was on XR simulator. Can this be avoided?

**Comment by ascoders** [comment]
Can you send a gif?

**Comment by jwhiddent3** [comment]
Nevermind- The screen tearing only affected simulator, it works perfectly on device
