### ISSUE TITLE
Tab Bar Obscures Zoomed Image

### ISSUE THREAD

**Issue by jwhiddent3** [ascoders/react-native-image-zoom#74]
I've tried a few different things to try to 'push up' the zoomed image, but nothing is working. When you zoom in to an image, the display cannot be panned to the very bottom. If you try to scroll to the bottom, it immediately jumps back up, and the bottom of the image is hidden by the tab bar (react-navigation). Is there a way to make sure that the zoomable content is confined to above the tab bar?

**Comment by dzek69** [comment]
you should provide correct cropHeight, it looks like you've just copied example code. calculate height without tab bar and provide it as cropHeight
